const str1 = document.getElementById('string-1')
const str2 = document.getElementById('string-2')
const str3 = document.getElementById('string-3')
const str4 = document.getElementById('string-4')
const str5 = document.getElementById('string-5')
const str6 = document.getElementById('string-6')

console.log(str3.innerText)
console.log(str5.innerText)
console.log(str2.innerText)
console.log(str6.innerText)
console.log(str4.innerText)
console.log(str1.innerText)
